<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    
    <parent>
       <groupId>org.broadleafcommerce</groupId>
       <artifactId>broadleaf-module-parent</artifactId>
       <version>1.0.19-M1</version>
    </parent>

    <name>BroadleafCommerce Google Storage</name>
    <description>Integration of Google Storage with Broadleaf Framework</description>
    <groupId>com.broadleafcommerce</groupId>
    <artifactId>broadleaf-google-storage</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <url>https://www.broadleafcommerce.com</url>

    <properties>
        <project.uri>${project.baseUri}</project.uri>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <blc.version>5.1.25-GA</blc.version>
        <google.cloud.bom.version>26.39.0</google.cloud.bom.version>
    </properties>

    <repositories>
        <repository>
            <id>enterprise-releases</id>
            <name>enterprise-releases</name>
            <url>https://nexus2.broadleafcommerce.org/nexus/content/groups/enterprise-releases/</url>
        </repository>
        <repository>
            <id>enterprise-snapshots</id>
            <name>enterprise-snapshots</name>
            <url>https://nexus2.broadleafcommerce.org/nexus/content/groups/enterprise-snapshots/</url>
        </repository>
    </repositories>
    <scm>
        <connection>scm:git:git@github.com:BroadleafCommerce/blc-google-storage.git</connection>
        <developerConnection>scm:git:git@github.com:BroadleafCommerce/blc-google-storage.git</developerConnection>
        <url>https://github.com/BroadleafCommerce/blc-google-storage</url>
        <tag>HEAD</tag>
    </scm>
    <licenses>
        <license>
            <name>Broadleaf End User License Agreement 1.1</name>
            <url>http://license.broadleafcommerce.org/commercial_license-1.1.txt</url>
            <distribution>repo</distribution>
            <comments>Broadleaf Commerce Commercial License</comments>
        </license>
    </licenses>
    <developers>
        <developer>
            <id>blcteam</id>
            <name>Broadleaf Commerce Team</name>
            <email>info@broadleafcommerce.com</email>
            <organization>Broadleaf Commerce</organization>
            <organizationUrl>https://www.broadleafcommerce.com</organizationUrl>
            <timezone>-6</timezone>
        </developer>
    </developers>
    <distributionManagement>
        <snapshotRepository>
            <id>snapshots</id>
            <url>https://nexus2.broadleafcommerce.org/nexus/content/repositories/google-storage-snapshots/</url>
        </snapshotRepository>
        <repository>
            <id>releases</id>
            <url>https://nexus2.broadleafcommerce.org/nexus/content/repositories/google-storage-releases/</url>
        </repository>
    </distributionManagement>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.google.cloud</groupId>
                <artifactId>libraries-bom</artifactId>
                <version>${google.cloud.bom.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>com.google.cloud</groupId>
            <artifactId>google-cloud-storage</artifactId>
        </dependency>
          <dependency>
            <groupId>org.broadleafcommerce</groupId>
            <artifactId>broadleaf-common</artifactId>
            <version>${blc.version}</version>
            <scope>compile</scope>
            <type>jar</type>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.broadleafcommerce</groupId>
            <artifactId>broadleaf-third-party-integration-config</artifactId>
            <version>default</version>
            <scope>test</scope>
            <type>jar</type>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-test</artifactId>
            <type>jar</type>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <type>jar</type>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
